spring.application.name=CoffeeShopIMS

spring.datasource.username=postgres
spring.datasource.password=6977
spring.datasource.url=jdbc:postgresql://localhost:5432/coffeeshop_inventory

spring.jpa.properties.hibernate.default_schema=coffeeshopims

spring.jpa.hibernate.ddl-auto=update